name: WAVI
favicon: null
layout_spectrum: 0.46478577866218984
typography_spectrum: 0.030479366658255458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9408318628557026
  lightness: 0.7295972579158843
  saturation: 0.9460120438598096
  rhythmicContrast: 0.445810423232615
purpose: []
